### ISSUE TITLE
paper can't found

### ISSUE THREAD

**Issue by w682511** [zhangzhengde0225/FINet#5]
your job is so great,i want read your paper,but the link is loss,can you give a new one? thank you very much!

**Comment by zhangzhengde0225** [comment]
Thank you for your attention. Our paper is in submission and will be available after some the time.

**Comment by zhangzhengde0225** [comment]
Thank you for your attention. Our paper is in under review and will be available after some the time. If you like this project, please star and watch the project, we will inform you once the paper is available

**Comment by zhangzhengde0225** [comment]
Thank you for your attention. Our paper is under review and will be available after some time. If you like this project, please star and watch it, we will inform you once the paper is available.
